name: twitter_sentiment
channels: 
  - default
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy==1.16.1
  - matplotlib==3.1.0
  - pandas
  - tensorflow-gpu
  - keras
  - xlwings
  - nltk
  - gensim
  - wordcloud
  - pip:
    
    - spacy
    - jupyter
    - sklearn
    - seaborn
    - bokeh
    - tweepy
    - python-dotenv
    - vaderSentiment
